"""creator_id upd

Revision ID: 31cd3667d47e
Revises: b324eea16f35
Create Date: 2025-07-21 12:34:21.553569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31cd3667d47e'
down_revision: Union[str, None] = 'b324eea16f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_groups_group_creator'), table_name='groups')
    op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
    op.drop_constraint(op.f('groups_group_creator_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'users', ['creator_id'], ['id'])
    op.drop_column('groups', 'group_creator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_group_creator_fkey'), 'groups', 'users', ['group_creator'], ['id'])
    op.drop_index(op.f('ix_groups_creator_id'), table_name='groups')
    op.create_index(op.f('ix_groups_group_creator'), 'groups', ['group_creator'], unique=False)
    op.drop_column('groups', 'creator_id')
    # ### end Alembic commands ###
