"""update foreignkey

Revision ID: a0f4467ce0cb
Revises: a4b513611802
Create Date: 2025-07-18 13:51:41.470373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f4467ce0cb'
down_revision: Union[str, None] = 'a4b513611802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    # ### end Alembic commands ###
