"""group_creator field

Revision ID: b324eea16f35
Revises: a0f4467ce0cb
Create Date: 2025-07-21 11:09:06.286512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b324eea16f35'
down_revision: Union[str, None] = 'a0f4467ce0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_creator', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_groups_group_creator'), 'groups', ['group_creator'], unique=False)
    op.create_foreign_key(None, 'groups', 'users', ['group_creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_index(op.f('ix_groups_group_creator'), table_name='groups')
    op.drop_column('groups', 'group_creator')
    # ### end Alembic commands ###
