"""string role

Revision ID: d9db434c52de
Revises: f5e521570560
Create Date: 2025-06-30 22:08:27.525359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9db434c52de'
down_revision: Union[str, None] = 'f5e521570560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'moderator', 'admin', name='user_role'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('user', 'moderator', 'admin', name='user_role'),
               existing_nullable=False)
    # ### end Alembic commands ###
